### ISSUE TITLE
[3.8.2] - Main attribute

### ISSUE THREAD

**Issue by VerifiedOrganic** [tombatossals/ol3-compiled#3]
The newly updated 3.8.2 branch is missing a bower file with the `main` attribute.

**Comment by dmishne** [comment]
Can you please create new release with the fixed bower file?

**Comment by tombatossals** [comment]
Hi, sorry this is a personal project, I would recommend you to depend on official openlayers project.

In any case, I have created a bower.json file and published it as "ol3-compiled" in bower registry. You have only available version v3.8.2, which is the version I'm using actually in my project.

**Comment by iwan-uschka** [comment]
Hey,
i really want to use https://github.com/tombatossals/angular-openlayers-directive.
But it isn't possible at the moment because it references to this dependency https://github.com/tombatossals/ol3-compiled.git#3.8.2.
It has an empty `main` attribute in its bower.json.
My gulp process crashes so i had to add the main files to the bower.json `main`attribute manually, which isn't a good solution.
Can you please fix this?
Thank you

**Comment by tombatossals** [comment]
Totally right @iwan-uschka, i think I have solved it now. Can you try again to confirm?

If if didn't work, please, post the log of the gulp process you're using.

**Comment by iwan-uschka** [comment]
Thank you! It works.
